In [1]:
# Önce Kaggle dan CarDekho örnek veri setini çekelim
import pandas as pd
url = "https://raw.githubusercontent.com/manishkr1754/CarDekho_Used_Car_Price_Prediction/main/notebooks/data/cardekho_dataset.csv"
df = pd.read_csv(url)
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [3]:
df.tail(10)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
15401,19531,Maruti Swift,Maruti,Swift,3,25000,Individual,Petrol,Automatic,22.00,1197,81.80,5,590000
15402,19533,Honda Amaze,Honda,Amaze,6,28000,Dealer,Diesel,Manual,25.80,1498,98.60,5,525000
15403,19534,Renault KWID,Renault,KWID,2,2700,Dealer,Petrol,Manual,25.17,799,53.30,5,395000
15404,19535,Maruti Ertiga,Maruti,Ertiga,5,56829,Dealer,Diesel,Manual,20.77,1248,88.80,7,895000
15405,19536,Hyundai Grand,Hyundai,Grand,5,9229,Dealer,Petrol,Manual,18.90,1197,82.00,5,545000
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [4]:
# Unnamed sütunu gereksiz onu düşürelim.
df = df.drop(columns=["Unnamed: 0"])

In [5]:
df.sample(1)

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
672,Toyota Innova,Toyota,Innova,9,25000,Individual,Diesel,Manual,12.99,2494,100.0,8,1050000

In [6]:
# Kategorik olanları hızlıca 0 veya 1 yapalım
df["transmission_type"] = df["transmission_type"].map({"Manual": 0, "Automatic": 1})

In [7]:
df["fuel_type"].nunique()

5

In [8]:
df["fuel_type"].unique()

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [9]:
df["fuel_type"].value_counts()

fuel_type
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: count, dtype: int64

In [10]:
df["seller_type"].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [11]:
# Çoklu seçenekler için get_dummies yapalım
df = pd.get_dummies(df, columns=["fuel_type", "seller_type"], drop_first=True)

In [12]:
df.sample(1)

,car_name,brand,model,vehicle_age,km_driven,transmission_type,mileage,engine,max_power,seats,selling_price,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,fuel_type_Petrol,seller_type_Individual,seller_type_Trustmark Dealer
8723,Maruti Swift,Maruti,Swift,1,15000,0,28.4,1248,74.0,5,700000,True,False,False,False,True,False

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   car_name                      15411 non-null  object
 1   brand                         15411 non-null  object
 2   model                         15411 non-null  object
 3   vehicle_age                   15411 non-null  int64
 4   km_driven                     15411 non-null  int64
 5   transmission_type             15411 non-null  int64
 6   mileage                       15411 non-null  float64
 7   engine                        15411 non-null  int64
 8   max_power                     15411 non-null  float64
 9   seats                         15411 non-null  int64
 10  selling_price                 15411 non-null  int64
 11  fuel_type_Diesel              15411 non-null  bool
 12  fuel_type_Electric            15411 non-null  bool
 13  fuel_type_LPG                 15411 non-null  bool
 14  fuel_type_Petrol              15411 non-null  bool
 15  seller_type_Individual        15411 non-null  bool
 16  seller_type_Trustmark Dealer  15411 non-null  bool
dtypes: bool(6), float64(2), int64(6), object(3)
memory usage: 1.4+ MB

In [14]:
# x ve y yi belirleyelim, ilk 3 sü
x = df.drop(columns=['selling_price'])
y = df['selling_price']

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [16]:
# car_name, brand ve model sütunlarını, fiyata göre ağırlıklarına göre sayısala çevireceğiz.
# target encoding
for col in ["brand", "model", "car_name"]:
  if col in x_train:
    m = y_train.groupby(x_train[col]).mean()
    x_train[f"{col}_enc"], x_test[f"{col}_enc"] = (
        x_train[col].map(m),
        x_test[col].map(m),
    )
    x_train.drop(columns=[col], inplace=True)
    x_test.drop(columns=[col], inplace=True)

x_train.fillna(y_train.mean(), inplace=True)
x_test.fillna(y_train.mean(), inplace=True)

In [17]:
x_train.shape[1]

16

In [18]:
# x_train hâlâ DataFrame iken sütunları kaydediyoruz
import json

json.dump(
    list(x_train.columns),
    open("columns.json", "w", encoding="utf-8"),
    ensure_ascii=False,
    indent=4,
)

In [19]:
# sayısal ve kategorik sütunların işlenmesi
from sklearn.compose import make_column_selector, make_column_transformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = make_column_transformer(
    (StandardScaler(), make_column_selector(dtype_include=["number"])),
    (
        OneHotEncoder(handle_unknown="ignore", sparse_output=False),
        make_column_selector(dtype_include=["object", "category"]),
    ),
)

In [20]:
x_train = preprocessor.fit_transform(x_train)
x_test = preprocessor.transform(x_test)

In [21]:
from sklearn.ensemble import (
    AdaBoostRegressor,
    GradientBoostingRegressor,
    RandomForestRegressor,
)
from sklearn.linear_model import (
    ElasticNet,
    Lasso,
    LinearRegression,
    Ridge,
    SGDRegressor,
)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor, RadiusNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor, ExtraTreeRegressor
from xgboost import XGBRegressor
import pandas as pd


def algo_test(x, y):
  # Bütün modelleri tanımlıyorum
  L = LinearRegression()
  R = Ridge()
  Lass = Lasso()
  E = ElasticNet()
  sgd = SGDRegressor()
  ETR = ExtraTreeRegressor()
  GBR = GradientBoostingRegressor()
  kn = KNeighborsRegressor()
  rkn = RadiusNeighborsRegressor(radius=1.0)
  ada = AdaBoostRegressor()
  dt = DecisionTreeRegressor()
  xgb = XGBRegressor()
  svr = SVR()
  mlp_regressor = MLPRegressor()

  algos = [L, R, Lass, E, sgd, ETR, GBR, ada, kn, dt, xgb, svr, mlp_regressor]
  algo_names = [
      "Linear",
      "Ridge",
      "Lasso",
      "ElasticNet",
      "SGD",
      "Extra Tree",
      "Gradient Boosting",
      "KNeighborsRegressor",
      "AdaBoost",
      "Decision Tree",
      "XGBRegressor",
      "SVR",
      "mlp_regressor",
  ]

  x_train, x_test, y_train, y_test = train_test_split(
      x, y, test_size=0.20, random_state=42
  )

  # Data Leakage engellemek için ölçeklendirme sadece train üzerinden yapılır
  scaler = MinMaxScaler()
  x_train = scaler.fit_transform(x_train)
  x_test = scaler.transform(x_test)

  r_squared = []
  rmse = []
  mae = []

  result = pd.DataFrame(columns=["R_Squared", "RMSE", "MAE"], index=algo_names)

  for algo in algos:
    try:
      p = algo.fit(x_train, y_train).predict(x_test)
      r_squared.append(r2_score(y_test, p))
      rmse.append(mean_squared_error(y_test, p) ** 0.5)
      mae.append(mean_absolute_error(y_test, p))
    except Exception:
      r_squared.append(None)
      rmse.append(None)
      mae.append(None)

  result.R_Squared = r_squared
  result.RMSE = rmse
  result.MAE = mae

  rtable = result.sort_values("R_Squared", ascending=False)
  return rtable

In [22]:
algo_test(x_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

                     R_Squared          RMSE            MAE
Linear                0.885110  3.768485e+05  181753.192932
Lasso                 0.885106  3.768541e+05  181746.358930
Extra Tree            0.884172  3.783826e+05  120217.693971
Ridge                 0.875173  3.928070e+05  182972.595407
Gradient Boosting     0.862535  4.122119e+05  109659.744188
SGD                   0.839910  4.448437e+05  192793.030797
KNeighborsRegressor   0.778754  5.229526e+05  282325.664530
Decision Tree         0.731403  5.762026e+05  126711.618005
AdaBoost              0.705852  6.029867e+05  118514.030819
XGBRegressor          0.656524  6.515881e+05  106977.085938
ElasticNet            0.084873  1.063569e+06  410509.686793
SVR                  -0.042293  1.135063e+06  401331.725036
mlp_regressor        -0.462135  1.344370e+06  759430.635369

In [23]:
# En iyi çıkan modelimizi pickle ile turşu yapıp json ile modele çeviriyoruz.
import json
import pickle
from sklearn.linear_model import LinearRegression

best_model = LinearRegression()
best_model.fit(x_train, y_train)

LinearRegression()

In [24]:
pickle.dump(best_model, open("car_model.pkl", "wb"))
pickle.dump(preprocessor, open("car_preprocessor.pkl", "wb"))